# Generated by Django 5.0 on 2023-12-18 18:44


#This migration file sets up the database tables for my project. 
# It creates tables for loan product details, sales projections, and pricing assumptions. 
# These tables store the financial inputs and outputs that my machine learning models use to predict loan loss rates and support business planning


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_id", models.CharField(max_length=5000)),
                ("payment_plan", models.CharField(max_length=5000)),
                (
                    "cost_per_credit",
                    models.DecimalField(decimal_places=2, max_digits=65),
                ),
                ("deposit", models.DecimalField(decimal_places=2, max_digits=65)),
                ("loan_duration", models.IntegerField()),
                (
                    "product_price",
                    models.DecimalField(decimal_places=2, max_digits=65),
                ),
                (
                    "product_price_weighted_llr_200",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                ("quality_of_sales", models.CharField(max_length=5000)),
                (
                    "deposit_to_price_ratio",
                    models.DecimalField(decimal_places=4, max_digits=65),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesProjection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_detail", models.CharField(max_length=255)),
                (
                    "anticipated_growth",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("price_change", models.DecimalField(decimal_places=2, max_digits=5)),
                ("total_volume_before", models.IntegerField()),
                ("total_volume_after", models.IntegerField()),
                (
                    "unit_price_before",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "unit_price_after",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "gross_revenue_before",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "gross_revenue_after",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "current_priced_cm2_before",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "current_priced_cm2_after",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "expected_cm2_revenue_before",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "expected_cm2_revenue_after",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("current_llr", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "llr_threshold_zero_sum",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LLRPricingAssumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instance_number", models.IntegerField(blank=True, null=True)),
                (
                    "cost_per_credit",
                    models.DecimalField(decimal_places=2, max_digits=65),
                ),
                ("loan_duration", models.IntegerField()),
                ("deposit", models.DecimalField(decimal_places=2, max_digits=65)),
                ("price", models.DecimalField(decimal_places=2, max_digits=65)),
                (
                    "deposit_to_price_ratio",
                    models.DecimalField(decimal_places=4, max_digits=65),
                ),
                (
                    "predicted_llr",
                    models.DecimalField(decimal_places=4, max_digits=65),
                ),
                (
                    "anticipated_growth",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "price_change",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("total_volume_before", models.IntegerField(blank=True, null=True)),
                ("total_volume_after", models.IntegerField(blank=True, null=True)),
                (
                    "unit_price_before",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "unit_price_after",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "gross_revenue_before",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "gross_revenue_after",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "current_priced_cm2_before",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "current_priced_cm2_after",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "expected_cm2_revenue_before",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "expected_cm2_revenue_after",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "current_llr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "llr_threshold_zero_sum",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "payment_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llr_assumptions",
                        to="basicConcepts.productdetail",
                    ),
                ),
            ],
        ),
    ]
