# Generated by Django 5.0 on 2023-12-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basicConcepts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llrpricingassumption",
            name="predicted_llr",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
