# Generated by Django 5.0 on 2024-01-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicConcepts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llrpricingassumption',
            name='cost_per_credit',
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
        migrations.AlterField(
            model_name='llrpricingassumption',
            name='deposit',
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
        migrations.AlterField(
            model_name='llrpricingassumption',
            name='deposit_to_price_ratio',
            field=models.DecimalField(decimal_places=4, max_digits=65),
        ),
        migrations.AlterField(
            model_name='llrpricingassumption',
            name='predicted_llr',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='llrpricingassumption',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='deposit_to_price_ratio',
            field=models.DecimalField(decimal_places=4, max_digits=65),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
    ]
