# Generated by Django 5.0 on 2024-01-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicConcepts', '0002_alter_llrpricingassumption_cost_per_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llrpricingassumption',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llrpricingassumption',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
