# Generated by Django 5.0 on 2024-01-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicConcepts', '0003_llrpricingassumption_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlanProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Payment Plan Name', max_length=255)),
                ('date', models.DateField(help_text='Projection Date')),
                ('product_cost', models.DecimalField(decimal_places=2, help_text='Product Cost', max_digits=10)),
                ('projection_amount', models.DecimalField(decimal_places=2, help_text='Projection Amount', max_digits=10)),
            ],
        ),
    ]
