# Generated by Django 5.0 on 2024-01-18 06:58

import django.utils.timezone
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicConcepts', '0004_paymentplanprojection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentplanprojection',
            name='date',
        ),
        migrations.RemoveField(
            model_name='paymentplanprojection',
            name='name',
        ),
        migrations.RemoveField(
            model_name='paymentplanprojection',
            name='projection_amount',
        ),
        migrations.AddField(
            model_name='paymentplanprojection',
            name='plan_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentplanprojection',
            name='projections',
            field=jsonfield.fields.JSONField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentplanprojection',
            name='product_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
