# Generated by Django 5.0 on 2024-01-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicConcepts', '0002_alter_llrpricingassumption_predicted_llr'),
        ('basicConcepts', '0005_remove_paymentplanprojection_date_and_more'),
    ]

    operations = [
    ]
