# Generated by Django 5.0 on 2024-01-22 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicConcepts', '0007_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llrpricingassumption',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicConcepts.reason'),
        ),
    ]
