# Generated by Django 5.0 on 2024-01-24 07:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basicConcepts", "0008_alter_llrpricingassumption_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="llrpricingassumption",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llr_assumptions_created",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="llrpricingassumption",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
